version: "3.8"

services:
  cudl-xtf:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMMIT_FULL_HASH: 90dc2468b4a963e7567c57d197c4c1b60ec27814
        VIEWER_PATH: ${VIEWER_PATH}
        XTF_PATH: ${XTF_PATH}
        SERVICES_PATH: ${SERVICES_PATH}
        SERVICES_KEY: ${SERVICES_KEY}
    #environment:
    #  DOCKER_HOST: ${DOCKER_HOST:-unix:///var/run/docker.sock}
    image: cudl/cudl-xtf:latest
    ports:
      - 8082:8080
    volumes:
      - cudl-data:/srv/cudl/cudl-data/json
      - xtf-webapp:/opt/xtf/
      - cudl-indices:/srv/cudl/xtf/
      # Provide access to our docker daemon to the build container so that it
      # can use it to build the image. Note: this is only for local runs, under
      # Bitbucket Pipelines DOCKER_HOST specifies a tcp:// URL for the docker
      # daemon.
      #- /var/run/docker.sock:/var/run/docker.sock

  xtf-indexer-cron:
    build:
      context: docker/text-indexer-cron
      dockerfile: Dockerfile
    image: cudl/xtf-indexer-cron:latest
    depends_on:
      - cudl-xtf
    volumes:
      - cudl-data:/srv/cudl/cudl-data/json
      - xtf-webapp:/opt/xtf/
      - cudl-indices:/srv/cudl/xtf/

volumes:
  cudl-data:
  xtf-webapp:
  cudl-indices:

